name: 'purge-jsdelivr-for-directory'
description:
  'Refresh the cache of jsdelivr for a folder in the current repository'
author: 'bling-yshs'

inputs:
  token:
    description: 'Repo token'
    default: ${{ github.token }}
    required: false
  path:
    description: 'Some directories in the current repository'
    required: true
  retry:
    description: 'retry times for each file'
    default: '10'
    required: false
  branchName:
    description: 'repo branch name, default is default branch of the repository'
    default: ''
    required: false

runs:
  using: node20
  main: dist/index.js
