name: 'purge-jsdelivr-for-directory'
description:
  'Refresh the cache of jsdelivr for a folder in the current repository'
author: 'bling-yshs'

inputs:
  token:
    description: 'Repo token, please type ${{ secrets.GITHUB_TOKEN }}'
    required: true
  path:
    description: 'Some directories in the current repository'
    required: true

runs:
  using: node20
  main: dist/index.js
