name: test action
on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: bling-yshs/purge-jsdelivr-for-directory@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            dist
            src
